In [9]:
import pandas as pd
import math, glob
import numpy as np

In [10]:
cd ..

/faststorage/project/CancerEvolution/Projects/janne_cns

In [11]:
import scripts.feature_func as feature

In [12]:
testfile = pd.read_table("~/TCGA/DerivedData/PanCancer/TCGA_ASCAT_RAW_PVL/ASCAT_TCGA/TCGA-02-0001.segments.raw.txt")
centAnno = pd.read_table("~/cns/data/chrominfo.snp6.txt", sep=' ')
ascat = pd.read_table("~/cns/data/filteredAscatRaw.txt", sep='\t')
gc = pd.read_table("~/cns/data/gc.content.txt", sep=' ')
repeats = pd.read_table("~/cns/data/repeats.txt", sep='\t')
# testfile = feature.relabelSC(testfile)

In [6]:
def makefeatfile(ascat, centromere, gccontent):

    feature_df = pd.DataFrame({
              'Sample': ascat['ID'],
                 'Chr': ascat['Chr'],
                  'CN': ascat['cn'], 
             'SegSize': ascat['End'] - ascat['Start'],
           'Dist2Cent': feature.getDist2Centromere(ascat, centromere),
              'SegVal': feature.getSegVal(ascat),
                 'LOH': feature.getLOH(ascat),
          'SizeDipSeg': feature.getSizeofDiploidSeg(ascat),
                'CpCN': feature.getCP(ascat),
           'Dist2nCNV': feature.getDist2CNV(ascat),
              'GCcSeg': feature.getGCcontent(ascat, gccontent)
     
    })

    feature_df = feature_df.groupby(['Sample', 'Chr'], as_index=False, sort=False).mean()
 
    return feature_df

df = makefeatfile(ascat, centAnno, gc)

df

KeyboardInterrupt

In [10]:
repeats

,#bin,swScore,milliDiv,milliDel,milliIns,genoName,genoStart,genoEnd,genoLeft,strand,repName,repClass,repFamily,repStart,repEnd,repLeft,id
0,1,2147,87,3,17,chr1,16777160,16777470,-232473151,+,AluSp,SINE,Alu,1,313,0,2
1,1,2626,28,0,0,chr1,25165800,25166089,-224084532,-,AluY,SINE,Alu,-22,289,1,4
2,1,626,312,185,59,chr1,33553606,33554646,-215695975,+,L2b,LINE,L2,2195,3356,-19,6
3,1,12545,132,15,48,chr1,50330063,50332153,-198918468,+,L1PA10,LINE,L1,15,2042,-4311,9
4,1,8050,8,1,9,chr1,58720067,58720973,-190529648,-,L1PA2,LINE,L1,-3,6152,5254,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5298125,585,1674,238,54,12,chr21_gl000210_random,25378,25875,-1807,+,MER74B,LTR,ERVL,95,612,-10,4
5298126,585,308,261,60,24,chr21_gl000210_random,26437,26596,-1086,-,MIRc,SINE,MIR,-60,208,53,4
5298127,585,475,286,7,57,chr21_gl000210_random,26881,27022,-660,-,MIRc,SINE,MIR,-104,164,31,4
5298128,585,371,362,0,13,chr21_gl000210_random,27296,27447,-235,+,HAL1-2a_MD,LINE,L1,2353,2501,-523,4
5298129,585,370,335,23,54,chr21_gl000210_random,27468,27682,0,+,HAL1-2a_MD,LINE,L1,2336,2530,-494,4

In [14]:
line1 = repeats[repeats['repFamily']=='L1'].reset_index()
line1['Chr'] = line1['genoName'].str.split('_').str[0]
# .str.extract('(\d+)', expand=False)
# line1['Chr'] = line1['Chr'].dropna().astype(int)

In [45]:
def no_repeats(ascat, line1):
    reps = [0] * len(ascat)
    line1 = line1[line1['repFamily']=='L1'].reset_index()
    line1['Chr'] = line1['genoName'].str.split('_').str[0].str.extract('(\d+)', expand=False)
    
    for i in range(0, len(ascat)):
        count = 0
        for j in range(0, len(line1)):
            if int(line1['Chr'][j]) == ascat['Chr'][i] and line1['genoStart'][j] >= ascat['Start'][i] and line1['genoStart'][j] < ascat['End'][i]:
                count += 1
            elif int(line1['Chr'][j]) == ascat['Chr'][i] and line1['genoStart'][j] < ascat['Start'][i] and line1['genoEnd'][j] > ascat['Start'][i]:
                count += 1
            else:
                continue
        reps[i] = count
    
    
    return reps

In [6]:
files = glob.glob('~/cns/data/*.segments.raw.txt')

In [ ]:
df = pd.read_table(files)

In [ ]:
print(df)

In [15]:
df = pd.read_table("/home/janneae/cns/steps/discretized_9_6bins.features")
df

,Sample,Chr,CN,SegSize,Dist2Cent,SegVal,LOH,SizeDipSeg,CpCN,Dist2nCNV,GCcSeg
0,TCGA-02-0001,1,3,6,3,4,0,2,2,6,4
1,TCGA-02-0001,2,3,5,4,6,0,1,5,2,3
2,TCGA-02-0001,3,3,5,4,3,0,1,3,4,3
3,TCGA-02-0001,4,2,6,2,1,0,3,2,2,1
4,TCGA-02-0001,5,2,5,6,2,0,2,5,3,2
...,...,...,...,...,...,...,...,...,...,...,...
176060,TCGA-ZX-AA5X,19,5,5,3,5,0,1,2,5,1
176061,TCGA-ZX-AA5X,20,4,6,1,3,0,1,1,6,6
176062,TCGA-ZX-AA5X,21,5,4,3,5,0,1,3,1,2
176063,TCGA-ZX-AA5X,22,4,5,2,4,0,1,1,5,6
176064,TCGA-ZX-AA5X,23,5,5,5,5,0,1,2,3,1

In [16]:
df['CN'] = 'CN_' + df['CN'].astype(str)
df['SegSize'] = 'SegSize_' + df['SegSize'].astype(str)
df['Dist2Cent'] = 'Dist2Cent_' + df['Dist2Cent'].astype(str)
df['SegVal'] = 'SegVal_' + df['SegVal'].astype(str)
df['LOH'] = 'LOH_' + df['LOH'].astype(str)
df['SizeDipSeg'] = 'SizeDipSeg_' + df['SizeDipSeg'].astype(str)
df['CpCN'] = 'CpCN_' + df['CpCN'].astype(str)
df['Dist2nCNV'] = 'Dist2CNV_' + df['Dist2nCNV'].astype(str)
df['GCcSeg'] = 'GCcSeg_' + df['GCcSeg'].astype(str)
# df['NoRepeats'] = 'NoRepeats_' + df['NoRepeats'].astype(str)
df

,Sample,Chr,CN,SegSize,Dist2Cent,SegVal,LOH,SizeDipSeg,CpCN,Dist2nCNV,GCcSeg
0,TCGA-02-0001,1,CN_3,SegSize_6,Dist2Cent_3,SegVal_4,LOH_0,SizeDipSeg_2,CpCN_2,Dist2CNV_6,GCcSeg_4
1,TCGA-02-0001,2,CN_3,SegSize_5,Dist2Cent_4,SegVal_6,LOH_0,SizeDipSeg_1,CpCN_5,Dist2CNV_2,GCcSeg_3
2,TCGA-02-0001,3,CN_3,SegSize_5,Dist2Cent_4,SegVal_3,LOH_0,SizeDipSeg_1,CpCN_3,Dist2CNV_4,GCcSeg_3
3,TCGA-02-0001,4,CN_2,SegSize_6,Dist2Cent_2,SegVal_1,LOH_0,SizeDipSeg_3,CpCN_2,Dist2CNV_2,GCcSeg_1
4,TCGA-02-0001,5,CN_2,SegSize_5,Dist2Cent_6,SegVal_2,LOH_0,SizeDipSeg_2,CpCN_5,Dist2CNV_3,GCcSeg_2
...,...,...,...,...,...,...,...,...,...,...,...
176060,TCGA-ZX-AA5X,19,CN_5,SegSize_5,Dist2Cent_3,SegVal_5,LOH_0,SizeDipSeg_1,CpCN_2,Dist2CNV_5,GCcSeg_1
176061,TCGA-ZX-AA5X,20,CN_4,SegSize_6,Dist2Cent_1,SegVal_3,LOH_0,SizeDipSeg_1,CpCN_1,Dist2CNV_6,GCcSeg_6
176062,TCGA-ZX-AA5X,21,CN_5,SegSize_4,Dist2Cent_3,SegVal_5,LOH_0,SizeDipSeg_1,CpCN_3,Dist2CNV_1,GCcSeg_2
176063,TCGA-ZX-AA5X,22,CN_4,SegSize_5,Dist2Cent_2,SegVal_4,LOH_0,SizeDipSeg_1,CpCN_1,Dist2CNV_5,GCcSeg_6
176064,TCGA-ZX-AA5X,23,CN_5,SegSize_5,Dist2Cent_5,SegVal_5,LOH_0,SizeDipSeg_1,CpCN_2,Dist2CNV_3,GCcSeg_1

In [ ]:
df.to_csv("../steps/discretized_9_6bins_tmp.features", header=True, index=None, sep='\t')